export const URL_SLUG_DATA = "URL_SLUG_DATA";
export const SEO_META_DATA = "SEO_META_DATA";
export const PRODUCTS_LIST_DATA = "PRODUCTS_LIST_DATA";
export const PRODUCTS_DETAIL_DATA = "PRODUCTS_DETAIL_DATA";
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const LOAD_CART = 'LOAD_CART';
export const CLEAR_CART = 'CLEAR_CART';
