export const POST_DATA = "POST_DATA";
export const CATEGORY_DATA = "CATEGORY_DATA";
export const BRAND_DATA = "BRAND_DATA";
export const PRODUCT_DATA = "PRODUCT_DATA";
export const SUB_CATEGORY_LIST = "SUB_CATEGORY_LIST";
export const VENDOR_LIST = "VENDOR_LIST";
export const CUSTOMER_LIST = "CUSTOMER_LIST";
export const PRODUCTS_DATA = "PRODUCTS_DATA";
export const UPDATE_VENDOR_FORM_DATA = "UPDATE_VENDOR_FORM_DATA";
export const UPDATE_CUSTOMER_FORM_DATA = "UPDATE_CUSTOMER_FORM_DATA";

export const SUB_CHILD_CATEGORY_LIST = "SUB_CHILD_CATEGORY_LIST";
export const UPDATE_PRODUCT_FORM_DATA = "UPDATE_PRODUCT_FORM_DATA";
export const UPDATE_CATEGORY_FORM_DATA = "UPDATE_CATEGORY_FORM_DATA";
export const UPDATE_SUB_CATEGORY_FORM_DATA = "UPDATE_SUB_CATEGORY_FORM_DATA";
export const UPDATE_BRAND_FORM_DATA = "UPDATE_BRAND_FORM_DATA";
export const UPDATE_URL_SLUG_FORM_DATA = "UPDATE_URL_SLUG_FORM_DATA";

export const PRODUCT_DETAILS_DATA_CP = "PRODUCT_DETAILS_DATA_CP";
export const PRODUCT_DATA_CP = "PRODUCT_DATA_CP";

export const PRODUCT_IMAGE_DATA = "PRODUCT_IMAGE_DATA";
export const ALL_ORDER_DATA = "ALL_ORDER_DATA";
export const ALL_CUSTOMER_DATA = "ALL_CUSTOMER_DATA";
export const ALL_COUPON_DATA = "ALL_COUPON_DATA";
export const OPEN_CLOSE_ORDER_DETAILS_AND_UPDATE_MODAL_POP_UP = "OPEN_CLOSE_ORDER_DETAILS_AND_UPDATE_MODAL_POP_UP";
export const RANGE_TYPE_CATEGORY_DATA = "RANGE_TYPE_CATEGORY_DATA";
export const SEO_REFERENCES_DATA = "SEO_REFERENCES_DATA";
export const SEO_REFERENCES_HTML_DROPDOWN = "SEO_REFERENCES_HTML_DROPDOWN";
export const URL_SLUG_DATA = "URL_SLUG_DATA";
export const FAQ_DATA = "FAQ_DATA";
export const UPDATE_FAQ_FORM_DATA = "UPDATE_FAQ_FORM_DATA";
export const IMPORT_REQUEST = "IMPORT_REQUEST";
export const IMPORT_SUCCESS = "IMPORT_SUCCESS";
export const IMPORT_FAILURE = "IMPORT_FAILURE";
